FROM gosonic/sonic:latest

## 复制配置文件
COPY config.yaml /sonic/conf/config.yaml

## 映射文件夹
# RUN ln -sf /mnt/auto/sonic /sonic
# RUN ln -sf /mnt/auto/database /sonic/database
# RUN ln -sf /mnt/oss /sonic/oss
#END